/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bean_GDATest */

#ifndef _Included_bean_GDATest
#define _Included_bean_GDATest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bean_RouteManager
 * Method:    startRoute
 * Signature: (IIIIIILjava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_bean_RouteManager_startIdrRoute
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jstring);

JNIEXPORT jobject JNICALL Java_bean_RouteManager_setMessage1
  (JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
